export const copy = {
  en: {
    brand: "ZawajLink",
    arabicBrand: "زواج لينك",
    tagline: "Empowering Brokers, Connecting Destinies",
    workspace: "Broker workspace",
    dashboard: "Dashboard",
    profiles: "Client Profiles",
    search: "Search & Match",
    proposals: "Proposals",
    crm: "Broker CRM",
    admin: "Admin",
    intake: "Profile Intake",
    newProfile: "New Profile",
    addProfile: "Add profile",
    recentProfiles: "Recent Profiles",
    followUps: "Follow-ups",
    searchPlaceholder: "Search name, city, nationality, community, phone",
    noProfiles: "No profiles found",
    noProfilesText: "Try a different filter or create a new profile.",
    selectProfile: "Select a profile",
    selectProfileText: "Review biodata, privacy controls, and match suggestions.",
    saveProfile: "Save profile",
    createProfile: "Create bride or groom biodata",
    operationalControls: "Operational Controls",
    secureMessaging: "Proposal workflow",
    secureMessagingText: "Track family-approved interest, meeting, and outcome stages.",
    privacy: "Privacy & compliance",
    privacyText: "Broker-only visibility, limited client view, admin review, and verification status.",
    billing: "Broker billing",
    billingText: "Monitor service fees, subscription readiness, and unpaid client payments.",
    login: "Sign in",
    register: "Register broker",
    logout: "Sign out",
    email: "Email",
    password: "Password",
    businessName: "Business name",
    contactName: "Contact name",
    phone: "Phone",
    country: "Country",
    city: "City",
    verificationPending: "Verification pending",
    verificationReady: "Account verified",
    savedSearches: "Saved searches",
    appointments: "Appointments",
    reports: "Reports"
  },
  ar: {
    brand: "ZawajLink",
    arabicBrand: "زواج لينك",
    tagline: "تمكين الوسطاء وربط النصيب",
    workspace: "مساحة عمل الوسيط",
    dashboard: "لوحة التحكم",
    profiles: "ملفات العملاء",
    search: "البحث والمطابقة",
    proposals: "المقترحات",
    crm: "إدارة علاقات الوسيط",
    admin: "الإدارة",
    intake: "إدخال البيانات",
    newProfile: "ملف جديد",
    addProfile: "إضافة ملف",
    recentProfiles: "أحدث الملفات",
    followUps: "المتابعات",
    searchPlaceholder: "ابحث بالاسم أو المدينة أو الجنسية أو المجتمع أو الهاتف",
    noProfiles: "لا توجد ملفات",
    noProfilesText: "غيّر المرشح أو أنشئ ملفاً جديداً.",
    selectProfile: "اختر ملفاً",
    selectProfileText: "راجع البيانات والخصوصية واقتراحات المطابقة.",
    saveProfile: "حفظ الملف",
    createProfile: "إنشاء بيانات عروس أو عريس",
    operationalControls: "أدوات التشغيل",
    secureMessaging: "سير المقترحات",
    secureMessagingText: "تتبع الاهتمام والاجتماعات والنتائج بموافقة العائلة.",
    privacy: "الخصوصية والامتثال",
    privacyText: "رؤية للوسيط فقط، عرض محدود للعميل، مراجعة إدارية، وحالة التحقق.",
    billing: "فوترة الوسيط",
    billingText: "متابعة رسوم الخدمة والاشتراكات والمدفوعات غير المكتملة.",
    login: "تسجيل الدخول",
    register: "تسجيل وسيط",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    businessName: "اسم المكتب",
    contactName: "اسم المسؤول",
    phone: "الهاتف",
    country: "الدولة",
    city: "المدينة",
    verificationPending: "بانتظار التحقق",
    verificationReady: "تم التحقق",
    savedSearches: "عمليات البحث المحفوظة",
    appointments: "المواعيد",
    reports: "التقارير"
  }
};
